name: sentence-transformer
channels:
  - defaults
dependencies:
  - python=3.9.21
  - pip
  # fall back to pip for anything not available in conda
  - pip:
    - matplotlib==3.9.4
    - numpy==2.0.2
    - pandas==2.2.3 
    - scikit_learn==1.6.1
    - torch==2.6.0
    - transformers==4.49.0